# Generated by Django 5.1.7 on 2025-03-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotíciaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituto', models.CharField(max_length=150)),
                ('noticia', models.TextField(max_length=1000)),
                ('data_de_criacao', models.DateTimeField(auto_now_add=True)),
                ('mostrar_noticia', models.BooleanField(default=False)),
                ('autor', models.CharField(max_length=20)),
            ],
        ),
    ]
